### ISSUE TITLE
switching between apps stops download

### ISSUE THREAD

**Issue by TD540** [nneonneo/iOS-Torrent-Client#2]
it seems when I switch away from the play.js app, it stops the torrent download…

do you perhaps know a way to prevent that?

thanks for your creative solution 🤪

**Comment by nneonneo** [comment]
Unfortunately not; iOS generally prevents applications from running in the background at all except in a very limited set of circumstances, and play.js does not appear to expose the APIs necessary to trigger background execution. Therefore, unless something fundamental changes in either play.js or iOS, this will not be possible (and indeed, it would not be possible with *any* app).

**Comment by TD540** [comment]
I noticed out I can just resume a torrent. Webtorrent just seems to continue with the downloaded parts.
